### ISSUE TITLE
Ideas for content on THL ktstrat main page

### ISSUE THREAD

**Issue by jtuomist** [City-of-Helsinki/cnh-ui#11]
Tämmöisen yläotsikon voisi laittaa:

Suomessa on tautitaakkaa vielä 
1 605 238
haittapainotettua elinvuotta.

Se on kasvanut vuodesta 2016 vuoteen 2017 1.1 %.

Ja sitten esittelytekstiksi:

Terveyden ja hyvinvoinnin laitoksen kansanterveysstrategia

THL:n tehtävänä on tuottaa tietoa päätöksenteon tueksi ja kansanterveyden parantamiseksi. THL päivittää osaamistaan jatkuvasti ja pyrkii varmistamaan, että oikeita asioita tehdään sekä talon sisällä että yhteiskunnassa yleisesti. Tällä sivustolla kokeillaan ajatusta, että kansanterveysstrategian sisältöä mietittäisiin avoimen verkkotyökalun avulla. Tarkoituksena on tunnistaa tarpeellisia toimenpiteitä, joilla THL voisi edistää kansanterveyttä. Lisäksi mietitään mittareita, joiden avulla toimenpniteiden toteutusta ja vaikutuksia voidaan seurata ja ohjata.

Teemojen ja organisaation osalta on se ongelma, että ne eivät ole THL:n kannalta relevantteja, enkä pääse muuttamaan niitä. THL:n organisaatiotiedot löytyvät täältä: https://thl.fi/fi/thl/organisaatio (tosin ilman lyhenteitä).

**Comment by terotic** [comment]
Let's move content related issues to other platforms. I close this for now.
