### ISSUE TITLE
Site certificate issue

### ISSUE THREAD

**Issue by emilyuhde** [City-of-Helsinki/cnh-ui#33]
When navigating to the site listed in the repo’s description, browsers give this message that there is a certificate issue.

![717E24A6-4F04-4A83-8EC1-8866E6308F5D](https://user-images.githubusercontent.com/4451556/67155129-e2d71d00-f2bd-11e9-937f-dae8b7316c02.png)

**Comment by juyrjola** [comment]
Thanks for the bug report! The official site has not yet been released, but I have fixed the certificate issue in any case.
