### ISSUE TITLE
The organisation link on an action page goes nowhere

### ISSUE THREAD

**Issue by jtuomist** [City-of-Helsinki/cnh-ui#9]
For example on page https://hnh.hel.ninja/action/58 Maka_Aska is the responsible organisation. Its name is a link but it does not go anywhere. I suggest that you make the link go to the main page (i.e., action list) where the actions are filtered according to the that organisation as a responsible organisation. Should be straightforward.

**Comment by terotic** [comment]
This fixed on current release
